[tool.poetry]
name = "openai-project"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
openai-agents = "*"
fastapi = "*"
agentic-radar = "*"
